server:
  port: 7600
  servlet:
    context-path: /proxy-ip

spring:
  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 300
        #最大阻塞等待时间(负数表示没限制)
        max-wait: 00
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    #连接超时时间
    timeout: 5000

# 异步线程配置
proxy_ip_async:
  executor:
    thread:
      # 配置核心线程数
      core_pool_size: 3
      # 配置最大线程数
      max_pool_size: 4
      # 配置队列大小
      queue_capacity: 99999
      # 配置线程池中的线程的名称前缀
      name:
        prefix: proxy-ip-async-service-